#### Text methods
https://pandas.pydata.org/docs/user_guide/text.html

In [11]:
import numpy as np
import pandas as pd

In [3]:
names = pd.Series(['andrew','bobo','claire','david','5'])

In [4]:
names

0    andrew
1      bobo
2    claire
3     david
4         5
dtype: str

In [5]:
names.str.upper()

0    ANDREW
1      BOBO
2    CLAIRE
3     DAVID
4         5
dtype: str

In [6]:
names.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [7]:
tech_finance=['GOOG,APPL,AMZN','JPM,BAC,GS']

In [8]:
len(tech_finance)

2

In [9]:
tickers = pd.Series(tech_finance)

In [10]:
tickers

0    GOOG,APPL,AMZN
1        JPM,BAC,GS
dtype: str

In [17]:
tickers.str.split(',').str[0]

0    GOOG
1     JPM
dtype: object

In [16]:
tickers.str.split(',',expand=True)

      0     1     2
0  GOOG  APPL  AMZN
1   JPM   BAC    GS

In [22]:
messy_names=pd.Series(['andrew ','bo;bo','claire  '])

In [23]:
messy_names

0     andrew
1       bo;bo
2    claire
dtype: str

In [26]:
messy_names.str.replace(';','').str.strip().str.capitalize()

0    Andrew
1      Bobo
2    Claire
dtype: str

In [30]:
def cleanup(name):
    name=name.replace(';','')
    name=name.strip()
    name=name.capitalize()
    return name

In [31]:
messy_names.apply(cleanup)

0    Andrew
1      Bobo
2    Claire
dtype: str

#### Time methods

In [3]:
from datetime import datetime

In [4]:
myyear = 2015
mymonth =1
myday=1
myhour=2
mymin=30
mysec=15

In [5]:
mydate = datetime(myyear,mymonth,myday)

In [6]:
mydate

datetime.datetime(2015, 1, 1, 0, 0)

In [7]:
mydatetime = datetime(myyear,mymonth,myday,myhour,mymin,mysec)

In [8]:
mydatetime

datetime.datetime(2015, 1, 1, 2, 30, 15)

In [9]:
mydatetime.year

2015

In [12]:
myser = pd.Series(['Nov 3,1990','2000-01-01',None])

In [13]:
myser

0    Nov 3,1990
1    2000-01-01
2           NaN
dtype: str

In [16]:
timeser = pd.to_datetime(myser)

C:\Users\KANCHANA SRIRAM\AppData\Local\Temp\ipykernel_23200\1142799102.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  timeser = pd.to_datetime(myser)

In [17]:
timeser

0   1990-11-03
1   2000-01-01
2          NaT
dtype: datetime64[us]

In [18]:
timeser[0].year

1990

In [20]:
obvi_euro_date ='31-12-2000'

In [21]:
pd.to_datetime(obvi_euro_date)

C:\Users\KANCHANA SRIRAM\AppData\Local\Temp\ipykernel_23200\163700324.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  pd.to_datetime(obvi_euro_date)

Timestamp('2000-12-31 00:00:00')

In [22]:
euro_date = '10-12-2000'

In [24]:
pd.to_datetime(euro_date) #given 10 dec, but it takes 12 Oct, check below function

Timestamp('2000-10-12 00:00:00')

In [25]:
pd.to_datetime(euro_date,dayfirst=True)

Timestamp('2000-12-10 00:00:00')

In [26]:
style_date= '12--Dec--2000'

In [27]:
pd.to_datetime(style_date,format='%d--%b--%Y')

Timestamp('2000-12-12 00:00:00')

In [28]:
custom_date='12th of Dec 2020'

In [29]:
pd.to_datetime(custom_date)

Timestamp('2020-12-12 00:00:00')

In [30]:
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv')

In [31]:
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [32]:
sales['DATE'] #dtype is str and not date

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: str

In [33]:
sales['DATE']=pd.to_datetime(sales["DATE"])

In [34]:
sales

          DATE  MRTSSM4453USN
0   1992-01-01           1509
1   1992-02-01           1541
2   1992-03-01           1597
3   1992-04-01           1675
4   1992-05-01           1822
..         ...            ...
335 2019-12-01           6630
336 2020-01-01           4388
337 2020-02-01           4533
338 2020-03-01           5562
339 2020-04-01           5207

[340 rows x 2 columns]

In [35]:
sales['DATE'] # now changed the dtype to datetime

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[us]

In [36]:
sales['DATE'][0].year

1992

In [38]:
sales

           DATE  MRTSSM4453USN
0    1992-01-01           1509
1    1992-02-01           1541
2    1992-03-01           1597
3    1992-04-01           1675
4    1992-05-01           1822
..          ...            ...
335  2019-12-01           6630
336  2020-01-01           4388
337  2020-02-01           4533
338  2020-03-01           5562
339  2020-04-01           5207

[340 rows x 2 columns]

In [40]:
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0])

In [41]:
sales['DATE'] # directly changed to datetime when reading csv file

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[us]

In [42]:
sales=sales.set_index("DATE")

In [43]:
sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [47]:
sales.resample(rule='YE').mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

In [48]:
sales = pd.read_csv('RetailSales_BeerWineLiquor.csv',parse_dates=[0])

In [49]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 340 entries, 0 to 339
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   DATE           340 non-null    datetime64[us]
 1   MRTSSM4453USN  340 non-null    int64
dtypes: datetime64[us](1), int64(1)
memory usage: 5.4 KB

In [50]:
sales['DATE'].dt.month

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int32