#### INPUT OUTPUT FILES

In [9]:
pip install numpy

Requirement already satisfied: numpy in c:\users\kanchana sriram\anaconda3\envs\requirements\lib\site-packages (2.4.2)
Note: you may need to restart the kernel to use updated packages.

### CSV Files

In [12]:
import pandas as pd
import numpy as np

In [2]:
pwd

'C:\\Users\\KANCHANA SRIRAM'

In [3]:
ls

 Volume in drive C is OS
 Volume Serial Number is D853-91DD

 Directory of C:\Users\KANCHANA SRIRAM

28-01-2026  23:24    <DIR>          .
04-01-2025  22:49    <DIR>          ..
25-01-2026  21:21    <DIR>          .anaconda
28-01-2026  23:24    <DIR>          .conda
28-01-2026  22:40                42 .condarc
25-01-2026  21:26    <DIR>          .continuum
28-01-2026  21:53    <DIR>          .ipynb_checkpoints
25-01-2026  23:17    <DIR>          .ipython
26-01-2026  21:13    <DIR>          .jupyter
12-01-2025  18:04    <DIR>          .vscode
25-01-2026  21:26    <DIR>          anaconda3
04-01-2025  23:04    <DIR>          Contacts
26-01-2026  23:36             3,471 dict_iteration_types.ipynb
22-03-2024  11:04    <DIR>          Documents
28-01-2026  23:18    <DIR>          Downloads
04-01-2025  23:04    <DIR>          Favorites
04-01-2025  23:04    <DIR>          Links
28-01-2026  09:45               177 movie_scores.csv
28-01-2026  17:25            17,727 mpg.csv
04-01-2025  23:04    <DIR>          Music
26-01-2026  21:51            23,170 numpy_creating_arrays.ipynb
26-01-2026  23:36            22,740 numpy_selection_indexing.ipynb
28-01-2026  22:37    <DIR>          OneDrive
28-01-2026  21:49            54,205 pandas_concatenate_merge.ipynb
27-01-2026  21:43            61,997 pandas_conditional_filter.ipynb
27-01-2026  21:18           162,385 pandas_dataframes.ipynb
28-01-2026  18:08           175,806 pandas_groupBy.ipynb
28-01-2026  14:56            47,834 pandas_missing_data.ipynb
27-01-2026  18:29             9,213 pandas_series.ipynb
28-01-2026  23:15            39,161 pandas_text_time_methods.ipynb
27-01-2026  22:56            98,626 pandas_useful_methods.ipynb
12-01-2025  19:20    <DIR>          PycharmProjects
28-01-2026  23:01             5,459 RetailSales_BeerWineLiquor.csv
04-01-2025  23:04    <DIR>          Saved Games
04-01-2025  23:04    <DIR>          Searches
06-01-2025  15:34                 0 Sti_Trace.log
27-01-2026  18:55            18,752 tips.csv
28-01-2026  23:24               948 Untitled.ipynb
26-01-2026  18:01                 0 untitled.py
24-01-2025  10:40    <DIR>          Videos
              19 File(s)        741,713 bytes
              21 Dir(s)  354,152,804,352 bytes free

In [6]:
df = pd.read_csv('example.csv',header=None)

In [7]:
df

    0   1   2   3
0   a   b   c   d
1   0   1   2   3
2   4   5   6   7
3   8   9  10  11
4  12  13  14  15

In [8]:
df = pd.read_csv('example.csv')

In [9]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [10]:
df = pd.read_csv('example.csv',index_col=0)

In [11]:
df

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [15]:
df.to_csv('newfile.csv',index=True)

In [16]:
new=pd.read_csv('newfile.csv')

In [17]:
new

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### HTML FILES

In [20]:
pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 419.4 kB/s eta 0:00:09
   ------- -------------------------------- 0.8/4.0 MB 635.5 kB/s eta 0:00:06
   ------- -------------------------------- 0.8/4.0 MB 635.5 kB/s eta 0:00:06
   ------------- -------------------------- 1.3/4.0 MB 836.5 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.0 MB 909.4 kB/s eta 0:00:03
   -------------------- ------------------- 2.1/4.0 MB 1.1 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.3 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.3 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 1.3 MB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 1.0 MB/s eta 0:00:02
   ---------------------------------------- 4.0/4.0 MB 1.3 MB/s  0:00:03
Installing collected packages: lxml
Successfully installed lxml-6.0.2
Note: you may need to restart the kernel to use updated packages.

In [21]:
url = "https://en.wikipedia.org/wiki/World_population"

In [23]:
tables = pd.read_html(url,
                      storage_options={"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
)

In [24]:
len(tables)

26

In [25]:
tables[0]

      Population     1     2     3     4     5     6     7     8     9    10
0           Year  1804  1927  1960  1974  1987  1999  2011  2022  2037  2057
1  Years elapsed     –   123    33    14    13    12    12    11    15    20

In [26]:
tables[1]

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [27]:
tables[1].columns

Index(['Region', '2022 (percent)', '2030 (percent)', '2050 (percent)'], dtype='str')

In [30]:
world_top = tables[1].set_index("Region")

In [31]:
world_top

,2022 (percent),2030 (percent),2050 (percent)
Region,,,
Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
World,7942,8512,9687

In [32]:
world_top.to_html('sample_table.html',index=True)

### EXCEL FILES

In [35]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [36]:
import openpyxl

In [37]:
df = pd.read_excel('my_excel_file.xlsx',sheet_name="First_Sheet")

In [38]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [40]:
wb = pd.ExcelFile('my_excel_file.xlsx')

In [41]:
wb.sheet_names

['First_Sheet']

In [42]:
excel_sheet_dict = pd.read_excel('my_excel_file.xlsx',sheet_name=None)

In [43]:
type(excel_sheet_dict)

dict

In [44]:
excel_sheet_dict.keys()

dict_keys(['First_Sheet'])

In [48]:
our_df = excel_sheet_dict['First_Sheet']

In [47]:
excel_sheet_dict

{'First_Sheet':     a   b   c   d
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15}

In [49]:
our_df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [50]:
our_df.to_excel('example.xlsx',sheet_name='First_Sheet',index=True)

### SQL DATABASE

In [1]:
pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.0.46-cp314-cp314-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.1-cp314-cp314-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\kanchana sriram\anaconda3\envs\requirements\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.0.46-cp314-cp314-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ------------------- -------------------- 1.0/2.1 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 12.7 MB/s  0:00:00
Downloading greenlet-3.3.1-cp314-cp314-win_amd64.whl (228 kB)
Installing collected packages: greenlet, sqlalchemy

   ---------------------------------------- 0/2 [greenlet]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   -------------------- ------------------- 1/2 [sqlalchemy]
   ---------------------------------------- 2/2 [sqlalchemy]

Successfully installed greenlet-3.3.1 sqlalchemy-2.0.46
Note: you may need to restart the kernel to use updated packages.

In [6]:
from sqlalchemy import create_engine

In [7]:
temp_db = create_engine('sqlite:///:memory:')

In [14]:
df = pd.DataFrame(data=np.random.randint(low=0,high=100,size=(4,4)), columns=['a','b','c','d'])

In [15]:
df

    a   b   c   d
0  66  83  30  71
1  20  60  89  77
2  11  25  59  87
3  73  84  14  11

In [16]:
df.to_sql(name='new_table',con=temp_db)

4

In [17]:
df.to_sql(name='new_table',con=temp_db)

ValueError: Table 'new_table' already exists.

In [19]:
new_df = pd.read_sql(sql='new_table',con=temp_db)

In [20]:
new_df

   index   a   b   c   d
0      0  66  83  30  71
1      1  20  60  89  77
2      2  11  25  59  87
3      3  73  84  14  11

In [21]:
pd.read_sql_query(sql="SELECT a,c FROM new_table", con=temp_db)

    a   c
0  66  30
1  20  89
2  11  59
3  73  14