#### Concatenate

In [1]:
import numpy as np
import pandas as pd

In [2]:
data_one = {'A':['A0','A1','A2','A3'],'B':['B0','B1','B2','B3']}

In [3]:
data_two = {'C':['C0','C1','C2','C3'],'D':['D0','D1','D2','D3']}

In [4]:
one = pd.DataFrame(data_one)

In [5]:
two = pd.DataFrame(data_two)

In [6]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [7]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [8]:
pd.concat([one,two],axis =1) # concat along columns

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [9]:
pd.concat([one,two],axis=0) #concat along rows

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [10]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [12]:
two.columns = one.columns

In [13]:
two

    A   B
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [15]:
mydf = pd.concat([one,two],axis=0)

In [16]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [17]:
mydf.index = range(len(mydf))

In [18]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

#### Merge (Inner,Outer, Left/Right)

In [19]:
registrations = pd.DataFrame({'reg_id':[1,2,3,4],'name':['Andrew','Bobo','Claire','David']})
logins = pd.DataFrame({'log_id':[1,2,3,4],'name':['Xavier','Andrew','Yolanda','Bobo']})

In [20]:
registrations

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [21]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

***INNER MERGE***

In [22]:
pd.merge(registrations,logins,how='inner',on='name')

   reg_id    name  log_id
0       1  Andrew       2
1       2    Bobo       4

In [24]:
pd.merge(logins,registrations,how='inner',on='name') #order doesnt matter for inner merge

   log_id    name  reg_id
0       2  Andrew       1
1       4    Bobo       2

***LEFT MERGE***

In [25]:
pd.merge(registrations,logins,how='left',on='name')

   reg_id    name  log_id
0       1  Andrew     2.0
1       2    Bobo     4.0
2       3  Claire     NaN
3       4   David     NaN

***RIGHT MERGE***

In [26]:
pd.merge(registrations,logins,how='right',on='name')

   reg_id     name  log_id
0     NaN   Xavier       1
1     1.0   Andrew       2
2     NaN  Yolanda       3
3     2.0     Bobo       4

***OUTER MERGE***

In [28]:
pd.merge(registrations,logins,how='outer',on='name') #order of tables doesnt matter as inner merge

   reg_id     name  log_id
0     1.0   Andrew     2.0
1     2.0     Bobo     4.0
2     3.0   Claire     NaN
3     4.0    David     NaN
4     NaN   Xavier     1.0
5     NaN  Yolanda     3.0

In [29]:
registrations = registrations.set_index('name')

In [30]:
registrations

        reg_id
name
Andrew       1
Bobo         2
Claire       3
David        4

In [31]:
logins

   log_id     name
0       1   Xavier
1       2   Andrew
2       3  Yolanda
3       4     Bobo

In [32]:
pd.merge(registrations,logins,left_index=True,right_on='name',how='inner')

   reg_id  log_id    name
1       1       2  Andrew
3       2       4    Bobo

In [33]:
registrations = registrations.reset_index()

In [34]:
registrations

     name  reg_id
0  Andrew       1
1    Bobo       2
2  Claire       3
3   David       4

In [35]:
registrations.columns=['reg_name','reg_id']

In [36]:
registrations

  reg_name  reg_id
0   Andrew       1
1     Bobo       2
2   Claire       3
3    David       4

In [38]:
results = pd.merge(registrations,logins,how='inner',left_on='reg_name',right_on='name')

In [39]:
results

  reg_name  reg_id  log_id    name
0   Andrew       1       2  Andrew
1     Bobo       2       4    Bobo

In [40]:
results.drop('reg_name',axis=1)

   reg_id  log_id    name
0       1       2  Andrew
1       2       4    Bobo

In [41]:
registrations.columns =['name','id']

In [43]:
logins.columns = ['id','name']

In [44]:
registrations

     name  id
0  Andrew   1
1    Bobo   2
2  Claire   3
3   David   4

In [45]:
logins

   id     name
0   1   Xavier
1   2   Andrew
2   3  Yolanda
3   4     Bobo

In [49]:
pd.merge(registrations,logins,how='inner',on='name')

     name  id_x  id_y
0  Andrew     1     2
1    Bobo     2     4

In [48]:
pd.merge(registrations,logins,how='inner',on='name',suffixes=('_reg','_log'))

     name  id_reg  id_log
0  Andrew       1       2
1    Bobo       2       4